level_five/appfolder/urls.py
from django.urls import path
from . import views
app_name = 'appfolder'
urlpatterns = [
    path('register/',views.register, name = 'register'),
    path('login/',views.user_login,name='login'),   # type: ignore
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

level_five/level_five/urls.py
from django.contrib import admin
from django.urls import path,include
from appfolder import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('appfolder/',include('appfolder.urls'))
]

level_five/appfolder/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
# the user field in UserInfo (a OneToOneField) acts as a bridge to connect a UserInfo instance to a User instance, 
# linking the two models without user belonging to User.
    user = models.OneToOneField(User,on_delete=models.CASCADE) 
    profile_pic = models.ImageField(blank=True,upload_to='Content/media')

    def __str__(self):
        return self.user.username
    

level_five/appfolder/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserInfo

class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('profile_pic',)
        

level_five/appfolder/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,logout,login # type: ignore
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse

def index(request):
    return render(request,'index.html')

def register(request):
    registered = False
    if request.method == 'POST':
        user_data = UserForm(data=request.POST)           # set the receievd data to the forms for validation
        user_pic = UserProfileInfoForm(data=request.POST)

        if user_data.is_valid() and user_pic.is_valid():
            validated_data = user_data.save()

            # Convert the password into hash for storage
            validated_data.set_password(validated_data.password)
            validated_data.save()

            validated_pic = user_pic.save(commit=False)  # Don't Save the pic in database
            validated_pic.user = validated_data          # Bridging them connects the extra data to the specific user

            if 'profile_pic' in request.FILES:           # see if the user provide pic and 'profile_pic' is field name given as a string   
                validated_pic.profile_pic = request.FILES['profile_pic'] # object.field = request.FILES['field name']

            validated_pic.save()
            registered = True
            
        else:
            print(user_data.errors,user_pic.errors)
    else:
        user_data = UserForm()
        user_pic = UserProfileInfoForm()

    return render(request,'register.html',{'user_data':user_data,
                                                 'user_pic':user_pic,
                                                 'register':registered}) 
 # {'register' : register} It doesn’t directly show True or False to the user;
 # it’s used in the template to control what’s displayed

def user_login(request):
    if request.method == 'POST':
        user_name = request.POST.get('username') # username in get is a key matches with name html form input (name="username")
        pass_word = request.POST.get('password')  # the value for the key is whatever the user is inputted.

        print(f"Received: username='{user_name}', password='{pass_word}'")
        # authenticate if username & password with registered username & password

        user_auth = authenticate(username = user_name,password = pass_word) 

        if user_auth:
            if user_auth.is_active:
                login(request,user_auth)                      # Sets request.user to user_auth
                return HttpResponseRedirect(reverse('index')) # redirect the user to index with navbar stays as log out 
                # index refers to the name='index' defined in your project’s urls.py
            
            else:                            # if the user account is not active              
                print('ACCOUNT NOT ACTIVE')
                
        else:                                # if the user authentication is failed
            print('SOMEONE LOG-IN FAILED')
            print('USERNAME: {} AND PASSWORD: {}'.format(user_name,pass_word))
            return HttpResponse('Invalid details')     # To display the user
        
    else:
        return render(request,'login.html')
    
@login_required           # only the logged in user can log out
def user_logout(request):
    logout(request)       # it automatically logs out the user, no need details about the user
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('YOU ARE LOGGED IN')




            


 

level_five/templates/htmls/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
        <!-- here appfolder is the name you creatied app urls.py -->
        <li><a href="{% url 'appfolder:register' %}">Register</a></li>

        <!-- user in templates corresponds to request.user, the currently logged-in user. -->
          {% if user.is_authenticated %}
          <!-- login(request, user_auth) sets request.user, which becomes user in templates -->

          <!-- user.is_authenricated placed here to control the navbar’s display across all pages that extend it. -->
              <li><a href="{% url 'appfolder:logout' %}">Log Out</a></li>
          {% else %}
          <!-- because of anchor tag it takes the current page to a corrsesponding page via GET -->
              <li><a href="{% url 'appfolder:login' %}">Log In</a></li>
        </div>
    </nav>
          {% endif %}
  

    <div class = 'container'>
          {% block body_block %}  
          {% endblock %}
    </div>

  </body>
</html>

level_five/templates/htmls/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1> Welcome to Home Page</h1>
    <h3> Go to Register page</h3>
</div>
{% endblock %}

level_five/templates/htmls/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<h1>LOGIN HERE</h1>
<!-- action checks the process of authentication via POST.get upon clicking the submit -->
<form action="{% url 'appfolder:login' %}" method="post">
    {% csrf_token %}
  <div class = 'jumbotron'>
    <label for="username">USERNAME</label>
    <input id='username' type="text" name="username">

    <label for="password">PASSWORD</label>
    <input id="password" type="password" name="password">

    <input type="submit" value="Submit">
  </div>
</form>
{% endblock %}

level_five/templates/htmls/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<div class = 'jumbotron'>
{% if register %}
   <h3> Thanks For Registering</h3>
{% else %}
   <h3> Fill out forms to register : </h3>
   <form method="POST" enctype="multipart/form-data">
       {% csrf_token %}
       {{ user_data.as_p }}
       {{ user_pic.as_p }}
       <input type="submit" value="Register">
   </form>
{% endif %}
</div>
{% endblock %}